defaults:
    medium: distribution
    source: mozilla
configs:
-   campaign: sample
    content: sample-001
    locales:
    - en-US
    - de
    - ru
    platforms:
    - win64-shippable
    - win32-shippable
    upload_to_candidates: true
-   campaign: test
    content: test-002
    locales:
    - de
    - en-CA
    - he
    - zh-TW
    platforms:
    - win64-shippable
    - win32-shippable
    upload_to_candidates: true
