defaults:
    medium: distribution
    source: mozilla
configs:
-   campaign: sample
    content: sample-001
    locales:
    - en-US
    - de
    - ru
    platforms:
    - win64
    - win32
    upload_to_candidates: true
-   campaign: test
    content: test-002
    locales:
    - de
    - en-CA
    - he
    platforms:
    - win64
    - win32
    upload_to_candidates: true
